name: Deploy website to FTP

on:
  # Runs on pushes targeting the default branch
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        # server-dir: ./
        protocol: ftp
        log-level: verbose
        # dry-run: true
